sudo: required
services:
  - docker

before_install:
  - docker build -t durgesh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run durgesh/react-test npm test -- --coverage

after_success:
  - docker build -t durgesh/multi-client -f ./client
  - docker build -t durgesh/multi-nginx -f ./nginx
  - docker build -t durgesh/multi-server -f ./server
  - docker build -t durgesh/multi-worker -f ./worker

  # Login to docker
  # Take the value of env DOCKER_PASSWORD and provide as input to the command on right side of pipe(|)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## Take the images and push the images to docker hub
  - docker push durgesh/multi-client
  - docker push durgesh/multi-nginx
  - docker push durgesh/multi-server
  - docker push durgesh/multi-worker
