sudo: required
services:
  - docker

before_install:
  - docker build -t durgesh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run durgesh/react-test npm test -- --coverage

after_success:
  # The docker image tag name should always be in a specific format only
  # Format: <docker username>/<image-name>:<optional version name>
  - docker build -t durgeshpatel317/multi-client ./client
  - docker build -t durgeshpatel317/multi-nginx ./nginx
  - docker build -t durgeshpatel317/multi-server ./server
  - docker build -t durgeshpatel317/multi-worker ./worker

  # Login to docker
  # Take the value of env DOCKER_PASSWORD and provide as input to the command on right side of pipe(|)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## Take the images and push the images to docker hub
  - docker push durgeshpatel317/multi-client
  - docker push durgeshpatel317/multi-nginx
  - docker push durgeshpatel317/multi-server
  - docker push durgeshpatel317/multi-worker

# For issues with deployment using travis ci 
# https://stackoverflow.com/questions/58774215/travis-ci-build-failed-awss3errorssignaturedoesnotmatch
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-ap-south-1-480015792483
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY